package enrich

import (
	"strings"
	"testing"

	"github.com/blotless/engine/domain"
)

func TestGoFunctionAndSnippet(t *testing.T) {
	src := []byte("package p\n\nfunc Hello() {\n\tx := \"a\u200b\"\n}\n")
	u := domain.Unit{Path: "a.go", Bytes: src, Language: domain.LangGo}
	zw := strings.Index(string(src), "a")
	// find the a in the string more carefully
	zw = strings.Index(string(src), "\"a") + 2
	fs := Findings(u, []domain.Finding{{
		RuleID: "unicode.zwsp",
		Span:   domain.Span{File: "a.go", Start: zw, End: zw + 3, Line: 4, Col: 8},
	}})
	if len(fs) != 1 {
		t.Fatal(fs)
	}
	if fs[0].Function != "Hello" {
		t.Fatalf("func=%q", fs[0].Function)
	}
	if !strings.Contains(fs[0].Snippet, "<U+200B>") {
		t.Fatalf("snippet=%q", fs[0].Snippet)
	}
	if fs[0].Kind != "string" {
		t.Fatalf("kind=%q", fs[0].Kind)
	}
}

func TestContainerSnippetUsesEvidence(t *testing.T) {
	u := domain.Unit{
		Path: "a.png", Kind: domain.KindImage, Language: domain.LangImage,
		Bytes: []byte{0x89, 'P', 'N', 'G'},
	}
	fs := Findings(u, []domain.Finding{{
		RuleID:   "container.png_metadata",
		Evidence: "Generated by Claude",
		Span:     domain.Span{File: "a.png", Start: 0, End: 1},
	}})
	if fs[0].Snippet != "Generated by Claude" {
		t.Fatalf("%q", fs[0].Snippet)
	}
}

func TestSymbolFromEvidence(t *testing.T) {
	u := domain.Unit{Path: "a.txt", Bytes: []byte("hello"), Language: domain.LangText}
	fs := Findings(u, []domain.Finding{{
		RuleID:   "unicode.zwsp",
		Evidence: "sym",
		Span:     domain.Span{File: "a.txt", Start: 1, End: 2, Line: 1, Col: 2},
	}})
	if fs[0].Symbol != "sym" {
		t.Fatalf("%q", fs[0].Symbol)
	}
}
