package stamp

import (
	"context"
	"testing"

	"github.com/blotless/engine/domain"
	"github.com/blotless/engine/internal/rules"
)

func TestCoAuthoredAndBoilerplate(t *testing.T) {
	if _, err := rules.Load(); err != nil {
		t.Fatal(err)
	}
	src := []byte("package p\n\n// Co-authored-by: Cursor <cursor@example.com>\n// Sure, here's a helper\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.go", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	var co, boil bool
	for _, f := range fs {
		if f.RuleID == "stamp.co_authored_by_ai" {
			co = true
		}
		if f.RuleID == "stamp.ai_boilerplate" {
			boil = true
		}
	}
	if !co || !boil {
		t.Fatalf("co=%v boil=%v %#v", co, boil, fs)
	}
}

func TestAllowProtoc(t *testing.T) {
	if _, err := rules.Load(); err != nil {
		t.Fatal(err)
	}
	src := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "x.pb.go", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range fs {
		if f.RuleID == "stamp.generated_by_ai" || f.RuleID == "stamp.ai_generated" {
			t.Fatalf("protoc flagged: %+v", f)
		}
	}
}

func TestPythonAndShellComments(t *testing.T) {
	if _, err := rules.Load(); err != nil {
		t.Fatal(err)
	}
	src := []byte("#!/usr/bin/env python3\n# Co-authored-by: Claude <x@y>\nx = 1  # Sure, here's a helper\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.py", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	var co, boil bool
	for _, f := range fs {
		if f.RuleID == "stamp.co_authored_by_ai" {
			co = true
		}
		if f.RuleID == "stamp.ai_boilerplate" {
			boil = true
		}
	}
	if !co || !boil {
		t.Fatalf("co=%v boil=%v %#v", co, boil, fs)
	}
}

func TestStringsNotStamps(t *testing.T) {
	if _, err := rules.Load(); err != nil {
		t.Fatal(err)
	}
	src := []byte("package p\nvar s = \"Sure, here's a helper\"\nvar t = `Co-authored-by: Cursor <x@y>`\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.go", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("string fixtures flagged: %#v", fs)
	}
}

func TestRawStringWithCommentText(t *testing.T) {
	if _, err := rules.Load(); err != nil {
		t.Fatal(err)
	}
	src := []byte("package p\nvar s = `x := 1 // Sure, here's a helper`\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{
		Path: "a.go", Bytes: src, Language: domain.LangGo,
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("raw string flagged: %#v", fs)
	}
}

func TestCommentAfterStringStillFlagged(t *testing.T) {
	if _, err := rules.Load(); err != nil {
		t.Fatal(err)
	}
	src := []byte("package p\nvar x = \"ok\" // Sure, here's a helper\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.go", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, f := range fs {
		if f.RuleID == "stamp.ai_boilerplate" {
			found = true
		}
	}
	if !found {
		t.Fatalf("comment after string missed: %#v", fs)
	}
}

func TestDetectorMeta(t *testing.T) {
	d := Detector{}
	if d.ID() != "stamp" || len(d.Families()) == 0 {
		t.Fatalf("id=%s", d.ID())
	}
}
