package stamp

import (
	"bytes"
	"context"
	"regexp"
	"strings"
	"unicode/utf8"

	"github.com/blotless/engine/domain"
	"github.com/blotless/engine/internal/astgo"
	"github.com/blotless/engine/internal/classify"
	"github.com/blotless/engine/internal/comment"
	"github.com/blotless/engine/internal/rules"
	"github.com/blotless/engine/ports"
)

var generatedAllow = regexp.MustCompile(`(?i)code generated by (protoc|easyjson|stringer|mockgen|wire|sqlc|oapi-codegen)|Code generated .* DO NOT EDIT`)

type lineRule struct {
	id string
	re *regexp.Regexp
}

var lineRules = []lineRule{
	{id: "stamp.co_authored_by_ai", re: regexp.MustCompile(`(?i)^\s*(?://|#|--|/\*|\*)?\s*Co-authored-by:\s*.*(Cursor|Copilot|Claude|ChatGPT|OpenAI|Devin|Gemini|Codex)\b`)},
	{id: "stamp.generated_by_ai", re: regexp.MustCompile(`(?i)^\s*(?://|#|--|/\*|\*)?\s*(Generated by|Generated with)\s+.*(Copilot|Cursor|Claude|ChatGPT|OpenAI|Devin|Gemini)\b`)},
	{id: "stamp.ai_generated", re: regexp.MustCompile(`(?i)^\s*(?://|#|--|/\*|\*|<!--)?\s*(AI-generated|Generated by AI|This (file|code) was generated by (an )?AI)\b`)},
	{id: "stamp.html_ai_comment", re: regexp.MustCompile(`(?i)<!--\s*(Copilot|Cursor|Claude|ChatGPT|OpenAI|Devin)\b.*?-->`)},
	{id: "stamp.ai_boilerplate", re: regexp.MustCompile(`(?i)(Sure, here'?s|As an AI|I'?d be happy to|Let me know if you need|Here is a simple implementation|Hope this helps!|Of course! Here's)`)},
}

// Detector finds known AI comment and VCS stamps.
type Detector struct{}

func (Detector) ID() string { return "stamp" }

func (Detector) Families() []domain.Family { return []domain.Family{domain.FamilyStamp} }

func (Detector) Scan(_ context.Context, u domain.Unit) ([]domain.Finding, error) {
	if !classify.TextPayload(u) {
		return nil, nil
	}
	head := u.Bytes
	if len(head) > 2048 {
		head = head[:2048]
	}
	allowGenerated := generatedAllow.Match(head)
	strSpans := goStringSpans(u)

	var out []domain.Finding
	start := 0
	for start <= len(u.Bytes) {
		rel := bytes.IndexByte(u.Bytes[start:], '\n')
		end := len(u.Bytes)
		next := len(u.Bytes)
		if rel >= 0 {
			end = start + rel
			next = end + 1
		}
		line := u.Bytes[start:end]
		cOff, region, inComment := comment.Line(line)
		if !inComment {
			if rel < 0 {
				break
			}
			start = next
			continue
		}
		spanEnd := next
		if next == len(u.Bytes) {
			spanEnd = end
		}
		for _, lr := range lineRules {
			if allowGenerated && (lr.id == "stamp.generated_by_ai" || lr.id == "stamp.ai_generated") {
				continue
			}
			if !lr.re.Match(region) {
				continue
			}
			if lr.id == "stamp.html_ai_comment" && !bytes.Contains(region, []byte("<!--")) {
				continue
			}
			abs := start + cOff
			if inGoString(abs, abs+len(region), strSpans) {
				continue
			}
			span := spanFor(u, abs, spanEnd)
			f := rules.Apply(domain.Finding{
				Span:     span,
				Evidence: trimEvidence(region),
			}, lr.id)
			out = append(out, f)
		}
		if rel < 0 {
			break
		}
		start = next
	}
	return out, nil
}

func goStringSpans(u domain.Unit) []astgo.Span {
	if u.Language != domain.LangGo && !strings.HasSuffix(strings.ToLower(u.Path), ".go") {
		return nil
	}
	f, err := astgo.Parse(u.Path, u.Bytes)
	if err != nil {
		return nil
	}
	return f.StringSpans()
}

func inGoString(start, end int, strs []astgo.Span) bool {
	for _, s := range strs {
		if start < s.End && s.Start < end {
			return true
		}
	}
	return false
}

func trimEvidence(line []byte) string {
	s := string(bytes.TrimSpace(line))
	if len(s) > 120 {
		return s[:120]
	}
	return s
}

func spanFor(u domain.Unit, start, end int) domain.Span {
	line, col := 1, 1
	i := 0
	for i < start && i < len(u.Bytes) {
		r, size := utf8.DecodeRune(u.Bytes[i:])
		if r == '\n' {
			line++
			col = 1
		} else {
			col++
		}
		i += size
	}
	return domain.Span{File: u.Path, Start: start, End: end, Line: line, Col: col}
}

var _ ports.Detector = Detector{}
