package container

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/binary"
	"testing"

	"github.com/blotless/engine/domain"
	"github.com/blotless/engine/internal/rules"
)

func TestPNGTextAI(t *testing.T) {
	load(t)
	data := minimalPNG(pngChunk("tEXt", []byte("Comment\x00Generated by Claude")))
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.png", Bytes: data, Kind: domain.KindImage, Language: domain.LangImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 || fs[0].RuleID != "container.png_metadata" {
		t.Fatalf("%#v", fs)
	}
	cleaned := []byte(fs[0].Replacement)
	if bytes.Contains(cleaned, []byte("Claude")) {
		t.Fatalf("claude remains")
	}
	if !bytes.HasPrefix(cleaned, pngSig) {
		t.Fatal("not png")
	}
}

func TestPNGInnocentTextKept(t *testing.T) {
	load(t)
	data := minimalPNG(pngChunk("tEXt", []byte("Title\x00logo")))
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.png", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("false positive: %#v", fs)
	}
}

func TestPNGInvalidChunk(t *testing.T) {
	load(t)
	bad := []byte{0, 0, 0, 0, 'B', 'A', 'D', 'X', 0, 0, 0, 0}
	data := append([]byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}, bad...)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.png", Bytes: data, Kind: domain.KindImage})
	if err != nil || len(fs) != 0 {
		t.Fatalf("%#v %v", fs, err)
	}
}

func TestInvalidZipDOCX(t *testing.T) {
	load(t)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.docx", Bytes: []byte("not a zip"), Kind: domain.KindContainer})
	if err != nil || len(fs) != 0 {
		t.Fatalf("%#v %v", fs, err)
	}
}

func TestJPEGCOMComment(t *testing.T) {
	load(t)
	com := jpegSeg(0xFE, []byte("Generated by Claude"))
	sos := []byte{0xFF, 0xDA, 0x00, 0x08, 0x01, 0x01, 0x00, 0x00, 0x3F, 0x00, 0x00, 0x00, 0xFF, 0xD9}
	data := append([]byte{0xFF, 0xD8}, com...)
	data = append(data, sos...)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.jpg", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestJPEGAPP1AI(t *testing.T) {
	load(t)
	app1Payload := append([]byte("Exif\x00"), []byte("Generated by OpenAI")...)
	app1seg := jpegSeg(0xE1, app1Payload)
	sos := []byte{0xFF, 0xDA, 0x00, 0x08, 0x01, 0x01, 0x00, 0x00, 0x3F, 0x00, 0x00, 0x00, 0xFF, 0xD9}
	data := append([]byte{0xFF, 0xD8}, app1seg...)
	data = append(data, sos...)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.jpg", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestJPEGAPP11(t *testing.T) {
	load(t)
	data := minimalJPEGAPP11()
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.jpg", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
	cleaned := []byte(fs[0].Replacement)
	if bytes.Contains(cleaned, []byte("c2pa")) {
		t.Fatal("c2pa remains")
	}
}

func TestWebPC2PA(t *testing.T) {
	load(t)
	data := minimalWebP(
		[]byte("VP8X"), []byte{0x04, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		[]byte("VP8 "), []byte("image-data"),
		[]byte("XMP "), []byte("generator=OpenAI"),
		[]byte("C2PA"), []byte("jumb c2pa manifest"),
	)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.webp", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
	cleaned := []byte(fs[0].Replacement)
	if bytes.Contains(cleaned, []byte("C2PA")) || bytes.Contains(cleaned, []byte("OpenAI")) {
		t.Fatal("webp metadata remains")
	}
	if binary.LittleEndian.Uint32(cleaned[4:8]) != uint32(len(cleaned)-8) {
		t.Fatal("riff size")
	}
}

func TestWebPPayloadNotFalsePositive(t *testing.T) {
	load(t)
	data := minimalWebP([]byte("VP8 "), []byte("ordinary pixels mentioning c2pa"))
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.webp", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("%#v", fs)
	}
}

func TestHTMLMixedCase(t *testing.T) {
	load(t)
	src := []byte(`<html><head>
<meta NAME="GENERATOR" CONTENT="WordPress 6.4">
<meta NAME="generator" CONTENT="Claude">
</head></html>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.html", Bytes: src, Kind: domain.KindText, Language: domain.LangHTML})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("want 1 AI meta, got %#v", fs)
	}
	if !bytes.Contains([]byte(fs[0].Evidence), []byte("Claude")) {
		t.Fatalf("evidence=%q", fs[0].Evidence)
	}
}

func TestMarkdownAIFrontMatter(t *testing.T) {
	load(t)
	src := []byte("---\ntitle: hello\ngenerator: Claude\n---\n# hi\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.md", Bytes: src, Kind: domain.KindText, Language: domain.LangMarkdown})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 || fs[0].RuleID != "container.md_front_matter" {
		t.Fatalf("%#v", fs)
	}
	if bytes.Contains([]byte(fs[0].Replacement), []byte("Claude")) {
		t.Fatal("generator remains")
	}
	if !bytes.Contains([]byte(fs[0].Replacement), []byte("title: hello")) {
		t.Fatal("title dropped")
	}
}

func TestMarkdownInnocentFrontMatter(t *testing.T) {
	load(t)
	src := []byte("---\ntitle: hello\n---\n# hi\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.md", Bytes: src, Language: domain.LangMarkdown})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("%#v", fs)
	}
}

func TestSVGMetadata(t *testing.T) {
	load(t)
	src := []byte(`<svg xmlns="http://www.w3.org/2000/svg"><metadata>xmp rdf: c2pa</metadata></svg>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.svg", Bytes: src, Kind: domain.KindText, Language: domain.LangHTML})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 || fs[0].RuleID != "container.svg_metadata" {
		t.Fatalf("%#v", fs)
	}
}

func TestSVGInnocent(t *testing.T) {
	load(t)
	src := []byte(`<svg xmlns="http://www.w3.org/2000/svg"><circle r="1"/></svg>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.svg", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("%#v", fs)
	}
}

func TestPDFProducer(t *testing.T) {
	load(t)
	src := []byte("%PDF-1.4\n1 0 obj\n<< /Producer (Claude) /Creator (Word) >>\nendobj\n%%EOF\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.pdf", Bytes: src, Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 || fs[0].RuleID != "container.pdf_metadata" {
		t.Fatalf("%#v", fs)
	}
	if bytes.Contains([]byte(fs[0].Replacement), []byte("Claude")) {
		t.Fatal("producer remains")
	}
}

func TestDOCXCreator(t *testing.T) {
	load(t)
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	w, err := zw.Create("word/document.xml")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := w.Write([]byte(`<?xml version="1.0"?><w:document></w:document>`)); err != nil {
		t.Fatal(err)
	}
	w, err = zw.Create("docProps/core.xml")
	if err != nil {
		t.Fatal(err)
	}
	core := `<?xml version="1.0"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:creator>Claude</dc:creator></cp:coreProperties>`
	if _, err := w.Write([]byte(core)); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.docx", Bytes: buf.Bytes(), Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 || fs[0].RuleID != "container.docx_metadata" {
		t.Fatalf("%#v", fs)
	}
	if bytes.Contains([]byte(fs[0].Replacement), []byte("Claude")) {
		t.Fatal("creator remains")
	}
}

func TestODTGenerator(t *testing.T) {
	load(t)
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	w, err := zw.Create("content.xml")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := w.Write([]byte(`<?xml version="1.0"?><office:document-content/>`)); err != nil {
		t.Fatal(err)
	}
	w, err = zw.Create("meta.xml")
	if err != nil {
		t.Fatal(err)
	}
	meta := `<?xml version="1.0"?><office:document-meta><meta:generator>Claude</meta:generator><dc:creator>Alice</dc:creator></office:document-meta>`
	if _, err := w.Write([]byte(meta)); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.odt", Bytes: buf.Bytes(), Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 || fs[0].RuleID != "container.odt_metadata" {
		t.Fatalf("%#v", fs)
	}
	if bytes.Contains([]byte(fs[0].Replacement), []byte("Claude")) {
		t.Fatal("generator remains")
	}
}

func TestUnknownFormat(t *testing.T) {
	load(t)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.bin", Bytes: []byte("nope")})
	if err != nil || len(fs) != 0 {
		t.Fatalf("%#v %v", fs, err)
	}
}

func TestDetectorMeta(t *testing.T) {
	d := Detector{}
	if d.ID() != "container" {
		t.Fatalf("id=%s", d.ID())
	}
	if len(d.Families()) == 0 {
		t.Fatal("families")
	}
}

func TestHTMLJSONLD(t *testing.T) {
	load(t)
	src := []byte(`<html><head><script type="application/ld+json">{"@type":"CreativeWork","digitalSourceType":"trainedAlgorithmicMedia"}</script></head></html>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.html", Bytes: src, Kind: domain.KindText, Language: domain.LangHTML})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestHTMLDataAIAttr(t *testing.T) {
	load(t)
	src := []byte(`<html><body><div data-ai-generated="true">x</div></body></html>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.html", Bytes: src, Language: domain.LangHTML})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestPNGKeepStructuralChunks(t *testing.T) {
	load(t)
	data := minimalPNG(
		pngChunk("gAMA", []byte{1, 2, 3, 4}),
		pngChunk("tEXt", []byte("Comment\x00Generated by Claude")),
	)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.png", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
	cleaned := []byte(fs[0].Replacement)
	if !bytes.HasPrefix(cleaned, pngSig) {
		t.Fatal("not png")
	}
}

func TestSVGCommentAI(t *testing.T) {
	load(t)
	src := []byte(`<svg><!-- Generated by Claude --></svg>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.svg", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestPDFStructuredAI(t *testing.T) {
	load(t)
	src := []byte("%PDF-1.4\n<< /Type /Catalog /AIStructured true >>\n%%EOF\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.pdf", Bytes: src, Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	_ = fs
}

func TestPDFXMPPacket(t *testing.T) {
	load(t)
	src := []byte("%PDF-1.4\n<?xpacket begin=\"\" id=\"x\"?><x:xmpmeta>Generated by Claude</x:xmpmeta><?xpacket end=\"w\"?> %%EOF\n")
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.pdf", Bytes: src, Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestPNGC2PAChunkType(t *testing.T) {
	load(t)
	data := minimalPNG(pngChunk("caBX", []byte("c2pa manifest")))
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.png", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestPNGICCPC2PAKept(t *testing.T) {
	load(t)
	data := minimalPNG(pngChunk("iCCP", []byte("c2pa profile")))
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.png", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("structural chunk kept: %#v", fs)
	}
}

func TestMalformedWebP(t *testing.T) {
	load(t)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.webp", Bytes: []byte("RIFF\x00\x00\x00\x00WEBPtrunc"), Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 0 {
		t.Fatalf("%#v", fs)
	}
}

func TestWebPNotWebPError(t *testing.T) {
	load(t)
	_, labels, err := stripWebP([]byte("not webp"))
	if err == nil || labels != "" {
		t.Fatalf("labels=%q err=%v", labels, err)
	}
}

func TestWebPErrStrings(t *testing.T) {
	if errNotWebP.Error() != "not WebP" || errMalformedWebP.Error() != "malformed WebP" {
		t.Fatal("webp error strings")
	}
}

func TestZipErrString(t *testing.T) {
	if errZipBudget.Error() != "zip decompressed size exceeds cap" {
		t.Fatal(errZipBudget.Error())
	}
}

func TestSVGNeutralXMPProvenance(t *testing.T) {
	load(t)
	src := []byte(`<svg xmlns="http://www.w3.org/2000/svg"><metadata><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">neutral</rdf:RDF></metadata></svg>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.svg", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestSVGXMPMetadata(t *testing.T) {
	load(t)
	src := []byte(`<svg xmlns="http://www.w3.org/2000/svg"><x:xmpmeta>Claude</x:xmpmeta></svg>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.svg", Bytes: src})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestHTMLC2PAMeta(t *testing.T) {
	load(t)
	src := []byte(`<html><head><meta name="c2pa" content="manifest"></head></html>`)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.html", Bytes: src, Language: domain.LangHTML})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestODTDropAIFile(t *testing.T) {
	load(t)
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	w, _ := zw.Create("content.xml")
	_, _ = w.Write([]byte(`<?xml version="1.0"?><office:document-content/>`))
	w, _ = zw.Create("meta.xml")
	_, _ = w.Write([]byte(`<?xml version="1.0"?><office:document-meta/>`))
	w, _ = zw.Create("Configurations2/accelerator/current.xml")
	_, _ = w.Write([]byte(`<config>Generated by Claude</config>`))
	_ = zw.Close()
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.odt", Bytes: buf.Bytes(), Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestDOCXAppProps(t *testing.T) {
	load(t)
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	w, _ := zw.Create("word/document.xml")
	_, _ = w.Write([]byte(`<?xml version="1.0"?><w:document/>`))
	w, _ = zw.Create("docProps/app.xml")
	_, _ = w.Write([]byte(`<?xml version="1.0"?><Properties><Application>Claude</Application><AppVersion>1</AppVersion></Properties>`))
	_ = zw.Close()
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.docx", Bytes: buf.Bytes(), Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
	if bytes.Contains([]byte(fs[0].Replacement), []byte("Claude")) {
		t.Fatal("application remains")
	}
}

func TestWebPICCPAI(t *testing.T) {
	load(t)
	data := minimalWebP(
		[]byte("VP8X"), []byte{0x20, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		[]byte("ICCP"), []byte("Generated by OpenAI"),
		[]byte("VP8 "), []byte("pixels"),
	)
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.webp", Bytes: data, Kind: domain.KindImage})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestFormatOfSVGInline(t *testing.T) {
	u := domain.Unit{Path: "x.txt", Bytes: []byte("  <svg xmlns=\"http://www.w3.org/2000/svg\"></svg>")}
	if formatOf(u) != "svg" {
		t.Fatalf("%q", formatOf(u))
	}
}

func TestDOCXCustomXML(t *testing.T) {
	load(t)
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	w, _ := zw.Create("word/document.xml")
	_, _ = w.Write([]byte(`<?xml version="1.0"?><w:document/>`))
	w, _ = zw.Create("customXml/item1.xml")
	_, _ = w.Write([]byte(`<root>ai</root>`))
	w, _ = zw.Create("[Content_Types].xml")
	_, _ = w.Write([]byte(`<Types><Override PartName="/customXml/item1.xml" ContentType="text/xml"/></Types>`))
	_ = zw.Close()
	fs, err := Detector{}.Scan(context.Background(), domain.Unit{Path: "a.docx", Bytes: buf.Bytes(), Kind: domain.KindContainer})
	if err != nil {
		t.Fatal(err)
	}
	if len(fs) != 1 {
		t.Fatalf("%#v", fs)
	}
}

func TestFormatOfMagic(t *testing.T) {
	u := domain.Unit{Path: "x.dat", Bytes: []byte{0xff, 0xd8, 0xff, 0xe0}}
	if formatOf(u) != "jpeg" {
		t.Fatalf("%q", formatOf(u))
	}
	u = domain.Unit{Path: "x.dat", Bytes: append([]byte("PK\x03\x04"), []byte("word/document.xml")...)}
	if formatOf(u) != "docx" {
		t.Fatalf("%q", formatOf(u))
	}
}

func TestApplyWholeUnchanged(t *testing.T) {
	raw := []byte("same")
	if fs := applyWhole(domain.Unit{Path: "a.png", Bytes: raw}, "container.png_metadata", "x", raw); fs != nil {
		t.Fatalf("%#v", fs)
	}
}

func load(t *testing.T) {
	t.Helper()
	if _, err := rules.Load(); err != nil {
		t.Fatal(err)
	}
}

func minimalPNG(extra ...[]byte) []byte {
	ihdr := make([]byte, 13)
	binary.BigEndian.PutUint32(ihdr[0:4], 1)
	binary.BigEndian.PutUint32(ihdr[4:8], 1)
	ihdr[8] = 8
	ihdr[9] = 2
	out := append([]byte(nil), pngSig...)
	out = append(out, pngChunk("IHDR", ihdr)...)
	for _, c := range extra {
		out = append(out, c...)
	}
	out = append(out, pngChunk("IEND", nil)...)
	return out
}

func minimalJPEGAPP11() []byte {
	app0 := []byte("JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00")
	app0seg := jpegSeg(0xE0, app0)
	payload := []byte("jumbf\x00c2pa-test")
	app11 := jpegSeg(0xEB, payload)
	sos := []byte{0xFF, 0xDA, 0x00, 0x08, 0x01, 0x01, 0x00, 0x00, 0x3F, 0x00, 0x00, 0x00, 0xFF, 0xD9}
	out := []byte{0xFF, 0xD8}
	out = append(out, app0seg...)
	out = append(out, app11...)
	out = append(out, sos...)
	return out
}

func jpegSeg(marker byte, payload []byte) []byte {
	n := len(payload) + 2
	out := []byte{0xFF, marker, byte(n >> 8), byte(n)}
	return append(out, payload...)
}

func minimalWebP(parts ...[]byte) []byte {
	var body []byte
	body = append(body, []byte("WEBP")...)
	for i := 0; i+1 < len(parts); i += 2 {
		fourcc, payload := parts[i], parts[i+1]
		body = append(body, fourcc...)
		var ln [4]byte
		binary.LittleEndian.PutUint32(ln[:], uint32(len(payload)))
		body = append(body, ln[:]...)
		body = append(body, payload...)
		if len(payload)&1 == 1 {
			body = append(body, 0)
		}
	}
	var sz [4]byte
	binary.LittleEndian.PutUint32(sz[:], uint32(len(body)))
	out := append([]byte("RIFF"), sz[:]...)
	return append(out, body...)
}
