package container

import (
	"bytes"
	"regexp"
	"strings"
	"unicode/utf8"

	"github.com/blotless/engine/domain"
)

var (
	c2paNeedles = [][]byte{
		[]byte("c2pa"), []byte("jumb"), []byte("c2ma"),
		[]byte("contentcredentials"), []byte("contentauth"), []byte("cai:"),
	}
	aiNeedles = [][]byte{
		[]byte("c2pa"), []byte("contentcredentials"),
		[]byte("digitalsourcetype"), []byte("trainedalgorithmicmedia"),
		[]byte("compositewithtrainedalgorithmicmedia"), []byte("algorithmicmedia"),
		[]byte("aigc"), []byte("ai generated"), []byte("generated by"),
		[]byte("claude"), []byte("anthropic"), []byte("openai"), []byte("synthid"),
		[]byte("dcterms:provenance"),
	}
	generatorAI = regexp.MustCompile(`(?i)claude|anthropic|openai|chatgpt|gemini|synthid|copilot|midjourney|dall.?e|stable.?diffusion|cursor|codex`)
	aiMetaName  = regexp.MustCompile(`(?i)generator|ai[-_ ]?generated|claude|anthropic|openai|gemini|synthid|c2pa|content.?credential|provenance|digital.?source|aigc`)
)

var aiFrontKeys = map[string]struct{}{
	"generator": {}, "ai": {}, "ai_generated": {}, "ai-generated": {},
	"claude": {}, "anthropic": {}, "openai": {}, "gemini": {}, "synthid": {},
	"c2pa": {}, "content_credentials": {}, "contentcredentials": {},
	"provenance": {}, "digital_source_type": {}, "digitalsourcetype": {},
	"created_with": {}, "createdwith": {}, "model": {}, "llm": {},
}

func containsAny(blob []byte, needles [][]byte) []string {
	low := bytes.ToLower(blob)
	var found []string
	seen := map[string]struct{}{}
	for _, n := range needles {
		if !bytes.Contains(low, bytes.ToLower(n)) {
			continue
		}
		s := string(n)
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		found = append(found, s)
	}
	return found
}

func looksC2PA(blob []byte) bool {
	return len(containsAny(blob, c2paNeedles)) > 0
}

func looksAI(blob []byte) bool {
	return len(containsAny(blob, aiNeedles)) > 0 || looksC2PA(blob)
}

func hitLabels(blob []byte) string {
	hits := append(containsAny(blob, c2paNeedles), containsAny(blob, aiNeedles)...)
	if len(hits) == 0 {
		return ""
	}
	if len(hits) > 6 {
		hits = hits[:6]
	}
	return strings.Join(hits, ", ")
}

func wholeFile(u domain.Unit, id, evidence, replacement string) domain.Finding {
	return domain.Finding{
		Span:        domain.Span{File: u.Path, Start: 0, End: len(u.Bytes), Line: 1, Col: 1},
		Evidence:    evidence,
		Replacement: replacement,
	}
}

func spanFor(u domain.Unit, start, end int) domain.Span {
	line, col := 1, 1
	i := 0
	for i < start && i < len(u.Bytes) {
		r, size := utf8.DecodeRune(u.Bytes[i:])
		if r == '\n' {
			line++
			col = 1
		} else {
			col++
		}
		i += size
	}
	return domain.Span{File: u.Path, Start: start, End: end, Line: line, Col: col}
}

func clip(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}
