package llm

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/blotless/engine/ports"
	"github.com/blotless/engine/rewrite"
)

const (
	defaultOllamaHost  = "127.0.0.1:11434"
	defaultManagedHost = "127.0.0.1:12434"
)

var (
	lookPath          = exec.LookPath
	probeURL          = "http://" + defaultOllamaHost
	managedHost       = defaultManagedHost
	startServe        = startOllamaServe
	killTree          = killProcessTree
	serveReadyWait    = 60 * time.Second
	existingProbeWait = 1500 * time.Millisecond
)

// Ollama talks to a local Ollama HTTP API.
// If Endpoint is set, it only connects (config mode).
// If Endpoint is empty, it reuses :11434, otherwise a single blot-managed
// server on :12434. A previous managed process (and its llama-server children)
// is stopped before a new one is started.
type Ollama struct {
	cfg    Config
	cmd    *exec.Cmd
	cancel context.CancelFunc
	pid    int
	owned  bool
	log    *slog.Logger
}

func newOllama(cfg Config) (*Ollama, error) {
	if cfg.Model == "" {
		cfg.Model = DefaultOllamaModel
	}
	log := cfg.Logger
	if log == nil {
		log = slog.New(slog.NewTextHandler(io.Discard, nil))
	}
	o := &Ollama{cfg: cfg, log: log}

	if ep := strings.TrimSpace(cfg.Endpoint); ep != "" {
		o.cfg.Endpoint = strings.TrimRight(ep, "/")
		if err := o.waitReady(cfg.Timeout); err != nil {
			return nil, fmt.Errorf("ollama: configured endpoint %s is not reachable: %w", o.cfg.Endpoint, err)
		}
		if err := o.ensureModel(); err != nil {
			return nil, err
		}
		return o, nil
	}

	if err := ping(probeURL, existingProbeWait); err == nil {
		o.cfg.Endpoint = strings.TrimRight(probeURL, "/")
		o.log.Info("using existing ollama", "endpoint", o.cfg.Endpoint)
		if err := o.ensureModel(); err != nil {
			return nil, err
		}
		return o, nil
	}

	reclaimManaged()
	managedURL := "http://" + managedHost
	if err := ping(managedURL, existingProbeWait); err == nil {
		o.cfg.Endpoint = strings.TrimRight(managedURL, "/")
		o.log.Info("using existing ollama", "endpoint", o.cfg.Endpoint)
		if err := o.ensureModel(); err != nil {
			return nil, err
		}
		return o, nil
	}

	bin, err := lookPath("ollama")
	if err != nil {
		return nil, fmt.Errorf("ollama: binary not found in PATH; install from https://ollama.com/download")
	}
	host := managedHost
	o.log.Info("starting ollama", "host", host)

	cmd, cancel, err := startServe(bin, host)
	if err != nil {
		return nil, fmt.Errorf("ollama: start serve: %w", err)
	}
	o.cmd = cmd
	o.cancel = cancel
	o.owned = true
	o.cfg.Endpoint = "http://" + host
	if cmd != nil && cmd.Process != nil {
		o.pid = cmd.Process.Pid
		_ = writePidFile(o.pid, o.cfg.Endpoint)
	}

	if err := o.waitReady(serveReadyWait); err != nil {
		_ = o.Close()
		return nil, fmt.Errorf("ollama: serve did not become ready on %s: %w", host, err)
	}
	if err := o.ensureModel(); err != nil {
		_ = o.Close()
		return nil, err
	}
	return o, nil
}

func (o *Ollama) Name() string { return "ollama" }

func (o *Ollama) Close() error {
	if o == nil || !o.owned {
		return nil
	}
	o.owned = false
	pid := o.pid
	if pid <= 0 && o.cmd != nil && o.cmd.Process != nil {
		pid = o.cmd.Process.Pid
	}
	if pid > 0 {
		if o.log != nil {
			o.log.Info("stopping ollama", "pid", pid)
		}
		killTree(pid)
	}
	if o.cancel != nil {
		o.cancel()
	}
	if o.cmd != nil && o.cmd.Process != nil {
		_, _ = o.cmd.Process.Wait()
	}
	clearPidFile()
	return nil
}

func reclaimManaged() {
	pid, _, ok := readPidFile()
	if !ok {
		return
	}
	killTree(pid)
	clearPidFile()
}

func (o *Ollama) Classify(ctx context.Context, in ports.ClassifyIn) (ports.ClassifyOut, error) {
	prompt := `You classify whether SOURCE CODE was written by an AI coding assistant (Cursor, Copilot, ChatGPT, Claude, etc.).
This is code, not chat. Ordinary human production code must be confidence none.

AI-generated signals: generic "New creates X" / "GetX fetches" comments, numbered identifier sequences (foo2) together with those, mixed camelCase+snake_case in Go, jsonschema on many fields, tutorial-generic names (data/result/handler), uniform scaffolding, little domain irregularity.

Human signals: uneven comments, historical quirks, mixed style, tight domain logic, names that are specific rather than tutorial-generic.

Return JSON only:
{"rule_suggestion":"heuristic.llm_classify","rationale":"uniform New-creates comments and scaffolding","confidence":"likely","agent":"none"}
If it is not clearly AI-generated, set confidence to none and rationale to not_ai.
Set agent to one of: cursor, claude, copilot, chatgpt, gemini, none.
Name an agent only from an explicit marker in the fragment (Co-authored-by, Generated by, a comment that names Cursor/Claude/Copilot). If the code only looks generated, agent must be none — do not guess.
File: ` + in.File + `
Style fingerprint (identifier n-grams / naming sequences): ` + in.Context + `
Fragment:
` + in.Fragment
	raw, err := o.generate(ctx, prompt)
	if err != nil {
		return ports.ClassifyOut{}, err
	}
	var out ports.ClassifyOut
	if err := json.Unmarshal(raw, &out); err != nil {
		return ports.ClassifyOut{}, nil
	}
	return out, nil
}

func (o *Ollama) Rewrite(ctx context.Context, in ports.RewriteIn) (ports.RewriteOut, error) {
	raw, err := o.generateOpts(ctx, rewritePrompt(in), 0.9, false)
	if err != nil {
		return ports.RewriteOut{}, err
	}
	return parseRewrite(raw), nil
}

func rewritePrompt(in ports.RewriteIn) string {
	return rewrite.BuildPrompt(in.Strength, in.Fragment, "", "")
}

func parseRewrite(raw []byte) ports.RewriteOut {
	var out ports.RewriteOut
	if err := json.Unmarshal(raw, &out); err == nil && strings.TrimSpace(out.Rewrite) != "" {
		return out
	}
	s := strings.TrimSpace(string(raw))
	s = strings.TrimPrefix(s, "```")
	if i := strings.Index(s, "\n"); i >= 0 && strings.Contains(s[:i], "json") {
		s = strings.TrimSpace(s[i+1:])
	}
	s = strings.TrimSuffix(s, "```")
	return ports.RewriteOut{Rewrite: strings.TrimSpace(s)}
}

type ollamaReq struct {
	Model   string         `json:"model"`
	Prompt  string         `json:"prompt"`
	Stream  bool           `json:"stream"`
	Format  string         `json:"format"`
	Options map[string]any `json:"options,omitempty"`
}

type ollamaResp struct {
	Response string `json:"response"`
}

type tagsResp struct {
	Models []struct {
		Name  string `json:"name"`
		Model string `json:"model"`
	} `json:"models"`
}

type pullReq struct {
	Name   string `json:"name"`
	Stream bool   `json:"stream"`
}

func (o *Ollama) generate(ctx context.Context, prompt string) ([]byte, error) {
	return o.generateOpts(ctx, prompt, 0, true)
}

func (o *Ollama) generateOpts(ctx context.Context, prompt string, temperature float64, jsonFormat bool) ([]byte, error) {
	req := ollamaReq{
		Model:   o.cfg.Model,
		Prompt:  prompt,
		Stream:  false,
		Options: map[string]any{"temperature": temperature},
	}
	if jsonFormat {
		req.Format = "json"
	}
	body, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}
	raw, err := o.post(ctx, "/api/generate", body, o.cfg.Timeout)
	if err != nil {
		return nil, err
	}
	var decoded ollamaResp
	if err := json.Unmarshal(raw, &decoded); err != nil {
		return nil, err
	}
	return []byte(strings.TrimSpace(decoded.Response)), nil
}

func (o *Ollama) ensureModel() error {
	names, err := o.listModels()
	if err != nil {
		return err
	}
	if hasModel(names, o.cfg.Model) {
		return nil
	}
	o.log.Info("pulling ollama model", "model", o.cfg.Model, "endpoint", o.cfg.Endpoint)
	body, err := json.Marshal(pullReq{Name: o.cfg.Model, Stream: false})
	if err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), o.cfg.PullTimeout)
	defer cancel()
	if _, err := o.post(ctx, "/api/pull", body, o.cfg.PullTimeout); err != nil {
		return fmt.Errorf("ollama: pull %s: %w", o.cfg.Model, err)
	}
	return nil
}

func (o *Ollama) listModels() ([]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), o.cfg.Timeout)
	defer cancel()
	raw, err := o.get(ctx, "/api/tags")
	if err != nil {
		return nil, err
	}
	var tags tagsResp
	if err := json.Unmarshal(raw, &tags); err != nil {
		return nil, fmt.Errorf("ollama: tags: %w", err)
	}
	var names []string
	for _, m := range tags.Models {
		if m.Name != "" {
			names = append(names, m.Name)
		}
		if m.Model != "" {
			names = append(names, m.Model)
		}
	}
	return names, nil
}

func hasModel(names []string, want string) bool {
	for _, n := range names {
		n = strings.Split(n, "@")[0]
		if n == want {
			return true
		}
	}
	return false
}

func (o *Ollama) waitReady(d time.Duration) error {
	return ping(o.cfg.Endpoint, d)
}

func ping(endpoint string, d time.Duration) error {
	deadline := time.Now().Add(d)
	var last error
	for time.Now().Before(deadline) {
		ctx, cancel := context.WithTimeout(context.Background(), 400*time.Millisecond)
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(endpoint, "/")+"/api/tags", nil)
		if err != nil {
			cancel()
			return err
		}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			last = err
			cancel()
			time.Sleep(150 * time.Millisecond)
			continue
		}
		_, _ = io.Copy(io.Discard, io.LimitReader(resp.Body, 4096))
		_ = resp.Body.Close()
		cancel()
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			return nil
		}
		last = fmt.Errorf("status %d", resp.StatusCode)
		time.Sleep(150 * time.Millisecond)
	}
	if last == nil {
		last = fmt.Errorf("timeout")
	}
	return last
}

func (o *Ollama) get(ctx context.Context, path string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, o.cfg.Endpoint+path, nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("ollama: %w", err)
	}
	defer resp.Body.Close()
	b, err := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("ollama: %s status %d: %s", path, resp.StatusCode, bytes.TrimSpace(b))
	}
	return b, nil
}

func (o *Ollama) post(ctx context.Context, path string, body []byte, timeout time.Duration) ([]byte, error) {
	if timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, o.cfg.Endpoint+path, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("ollama: %w", err)
	}
	defer resp.Body.Close()
	b, err := io.ReadAll(io.LimitReader(resp.Body, 32<<20))
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("ollama: %s status %d: %s", path, resp.StatusCode, bytes.TrimSpace(b))
	}
	return b, nil
}

func freePort() (int, error) {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return 0, err
	}
	defer ln.Close()
	addr, ok := ln.Addr().(*net.TCPAddr)
	if !ok {
		return 0, fmt.Errorf("unexpected addr %T", ln.Addr())
	}
	return addr.Port, nil
}

func startOllamaServe(bin, host string) (*exec.Cmd, context.CancelFunc, error) {
	ctx, cancel := context.WithCancel(context.Background())
	cmd := exec.CommandContext(ctx, bin, "serve")
	cmd.Env = append(os.Environ(), "OLLAMA_HOST="+host)
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	configureServeCmd(cmd)
	if err := cmd.Start(); err != nil {
		cancel()
		return nil, nil, err
	}
	return cmd, cancel, nil
}

var _ ports.LLM = (*Ollama)(nil)
